#!/usr/bin/env bash

# Updating package lists and installing nginx
apt-get -y update
apt-get -y install nginx

# Setting ownership for index.html
INDEX_HTML="/var/www/html/index.html"
chown $USER:$USER "$INDEX_HTML"

# Creating index.html with "Hello World!"
echo "Hello World!" > "$INDEX_HTML"

# Restarting nginx without systemctl
kill -s HUP $(pgrep -f "nginx: master process")
