#!/usr/bin/env bash
# Update package lists and install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create index.html with "Hello World!" content
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null

# Configure redirection with a 301 Moved Permanently status code
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'

# Restart nginx to apply the changes
sudo service nginx restart
