#!/bin/bash
# Update the package lists and configures web01 with web02
sudo apt update

# Install Nginx if not already installed
sudo apt install -y nginx

# Configure Nginx to add custom HTTP response header
cat <<EOF | sudo tee /etc/nginx/sites-available/custom-header
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        # Add custom HTTP response header
        add_header X-Served-By \$hostname;
        try_files \$uri \$uri/ =404;
    }
}

EOF

# Create a symlink to enable the site
sudo ln -s /etc/nginx/sites-available/custom-header /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo systemctl reload nginx
