#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 257034-web-01 52.91.153.57:80 check
    server 257034-web-02 	34.227.101.246:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
